### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 3prm3** [Ladysnake/Effective#49]
[08/01/2022 19:26:14 PM] [Render thread/INFO] Stopping worker threads
[08/01/2022 19:26:23 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[08/01/2022 19:26:23 PM] 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2022 19:26:23 PM] 	at java.util.HashMap$KeyIterator.next(HashMap.java:1620)
[08/01/2022 19:26:23 PM] 	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:34)
[08/01/2022 19:26:23 PM] 	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121)
[08/01/2022 19:26:23 PM] 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.world.ClientWorld.handler$cii000$tickWorldAfterBlockEntities(ClientWorld:4100)
[08/01/2022 19:26:23 PM] 	at net.minecraft.world.World.tickBlockEntities(World:483)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:205)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1751)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
[08/01/2022 19:26:23 PM] 	at net.minecraft.client.main.Main.main(Main:238)
[08/01/2022 19:26:23 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/01/2022 19:26:23 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[08/01/2022 19:26:23 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/01/2022 19:26:23 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[08/01/2022 19:26:23 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[08/01/2022 19:26:23 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[08/01/2022 19:26:23 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[08/01/2022 19:26:23 PM] [Render thread/FATAL] Unreported exception thrown!
[08/01/2022 19:26:24 PM] ---- Minecraft Crash Report ----
[08/01/2022 19:26:24 PM] // Don't do that.
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] Time: 1/8/22, 7:26 PM
[08/01/2022 19:26:24 PM] Description: Unexpected error
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] java.util.ConcurrentModificationException
[08/01/2022 19:26:24 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[08/01/2022 19:26:24 PM] 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2022 19:26:24 PM] 	at java.util.HashMap$KeyIterator.next(HashMap.java:1620)
[08/01/2022 19:26:24 PM] 	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:34)
[08/01/2022 19:26:24 PM] 	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.world.ClientWorld.handler$cii000$tickWorldAfterBlockEntities(ClientWorld:4100)
[08/01/2022 19:26:24 PM] 	at net.minecraft.world.World.tickBlockEntities(World:483)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:205)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1751)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.main.Main.main(Main:238)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/01/2022 19:26:24 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[08/01/2022 19:26:24 PM] ---------------------------------------------------------------------------------------
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] -- Head --
[08/01/2022 19:26:24 PM] Thread: Render thread
[08/01/2022 19:26:24 PM] Stacktrace:
[08/01/2022 19:26:24 PM] 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2022 19:26:24 PM] 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
[08/01/2022 19:26:24 PM] 	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:34)
[08/01/2022 19:26:24 PM] 	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111)
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_638.handler$cii000$tickWorldAfterBlockEntities(class_638.java:4100)
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_1937.method_18471(class_1937.java:483)
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_638.method_18116(class_638.java:205)
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] -- Affected level --
[08/01/2022 19:26:24 PM] Details:
[08/01/2022 19:26:24 PM] 	All players: 1 total; [class_746['**MINECRAFTUSERNAME**'/23, l='ClientWorld minecraft:overworld', x=3109.54, y=97.97, z=1931.49]]
[08/01/2022 19:26:24 PM] 	Chunk stats: Client Chunks (ImmPtl) 249
[08/01/2022 19:26:24 PM] 	Level dimension: minecraft:overworld
[08/01/2022 19:26:24 PM] 	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[08/01/2022 19:26:24 PM] 	Level time: 893219 game time, 132554 day time
[08/01/2022 19:26:24 PM] 	Server brand: fabric
[08/01/2022 19:26:24 PM] 	Server type: Integrated singleplayer server
[08/01/2022 19:26:24 PM] Stacktrace:
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_638.method_8538(class_638.java:408)
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_310.method_1587(class_310.java:2402)
[08/01/2022 19:26:24 PM] 	at net.minecraft.class_310.method_1514(class_310.java:757)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.main.Main.main(Main.java:238)
[08/01/2022 19:26:24 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/01/2022 19:26:24 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[08/01/2022 19:26:24 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/01/2022 19:26:24 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] -- Last reload --
[08/01/2022 19:26:24 PM] Details:
[08/01/2022 19:26:24 PM] 	Reload number: 1
[08/01/2022 19:26:24 PM] 	Reload reason: initial
[08/01/2022 19:26:24 PM] 	Finished: Yes
[08/01/2022 19:26:24 PM] 	Packs: Default, Fabric Mods, fabric-copper-golem/copper_golem, fabric-diagonal-panes/default
[08/01/2022 19:26:24 PM] 
[08/01/2022 19:26:24 PM] -- System Details --
[08/01/2022 19:26:24 PM] Details:
[08/01/2022 19:26:24 PM] 	Minecraft Version: 1.18.1
[08/01/2022 19:26:24 PM] 	Minecraft Version ID: 1.18.1
[08/01/2022 19:26:24 PM] 	Operating System: Windows 10 (amd64) version 10.0
[08/01/2022 19:26:24 PM] 	Java Version: 17.0.1, Microsoft
[08/01/2022 19:26:24 PM] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[08/01/2022 19:26:24 PM] 	Memory: 1614554064 bytes (1539 MiB) / 5368709120 bytes (5120 MiB) up to 5368709120 bytes (5120 MiB)
[08/01/2022 19:26:24 PM] 	CPUs: 8
[08/01/2022 19:26:24 PM] 	Processor Vendor: AuthenticAMD
[08/01/2022 19:26:24 PM] 	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
[08/01/2022 19:26:24 PM] 	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
[08/01/2022 19:26:24 PM] 	Microarchitecture: Zen / Zen+
[08/01/2022 19:26:24 PM] 	Frequency (GHz): 2.10
[08/01/2022 19:26:24 PM] 	Number of physical packages: 1
[08/01/2022 19:26:24 PM] 	Number of physical CPUs: 4
[08/01/2022 19:26:24 PM] 	Number of logical CPUs: 8
[08/01/2022 19:26:24 PM] 	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
[08/01/2022 19:26:24 PM] 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
[08/01/2022 19:26:24 PM] 	Graphics card #0 VRAM (MB): 2048.00
[08/01/2022 19:26:24 PM] 	Graphics card #0 deviceId: 0x15d8
[08/01/2022 19:26:24 PM] 	Graphics card #0 versionInfo: DriverVersion=26.20.11002.13003
[08/01/2022 19:26:24 PM] 	Memory slot #0 capacity (MB): 4096.00
[08/01/2022 19:26:24 PM] 	Memory slot #0 clockSpeed (GHz): 2.40
[08/01/2022 19:26:24 PM] 	Memory slot #0 type: DDR4
[08/01/2022 19:26:24 PM] 	Memory slot #1 capacity (MB): 4096.00
[08/01/2022 19:26:24 PM] 	Memory slot #1 clockSpeed (GHz): 2.40
[08/01/2022 19:26:24 PM] 	Memory slot #1 type: DDR4
[08/01/2022 19:26:24 PM] 	Virtual memory max (MB): 24449.98
[08/01/2022 19:26:24 PM] 	Virtual memory used (MB): 18759.25
[08/01/2022 19:26:24 PM] 	Swap memory total (MB): 18432.00
[08/01/2022 19:26:24 PM] 	Swap memory used (MB): 4888.46
[08/01/2022 19:26:24 PM] 	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms1024M -Xmx5120M -XX:MetaspaceSize=448M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
[08/01/2022 19:26:24 PM] 	Fabric Mods: 
[08/01/2022 19:26:24 PM] 		additionaladditions: Additional Additions 3.0.1
[08/01/2022 19:26:24 PM] 		adorn: Adorn 3.1.0+1.18.1
[08/01/2022 19:26:24 PM] 		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
[08/01/2022 19:26:24 PM] 		advancednetherite: Advanced Netherite 1.2.0-1.18
[08/01/2022 19:26:24 PM] 		advancementframes: Advancement Frames 1.18-1.5.0
[08/01/2022 19:26:24 PM] 		ae2: Applied Energistics 2 10.0.0-beta.4
[08/01/2022 19:26:24 PM] 		alternatecurrent: Alternate Current 1.1.0
[08/01/2022 19:26:24 PM] 		amecs: Amecs 1.3.4+mc.1.18-pre1
[08/01/2022 19:26:24 PM] 		amecsapi: Amecs API 1.3.0+mc1.18-pre1
[08/01/2022 19:26:24 PM] 		ancientgateways: Ancient Gateways 1.2.0
[08/01/2022 19:26:24 PM] 		animatica: Animatica 0.2+1.18
[08/01/2022 19:26:24 PM] 		apples: Apples & Carrots 1.5
[08/01/2022 19:26:24 PM] 		appleskin: AppleSkin mc1.18-2.2.0
[08/01/2022 19:26:24 PM] 		aqupdcaracal: Caracal mob 1.18-1.3.5
[08/01/2022 19:26:24 PM] 		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
[08/01/2022 19:26:24 PM] 		arcanus: Arcanus 1.25
[08/01/2022 19:26:24 PM] 		architectury: Architectury 3.2.63
[08/01/2022 19:26:24 PM] 		artifality: Artifality 0.5.0
[08/01/2022 19:26:24 PM] 		artisanat: Artisanat 2.2.1
[08/01/2022 19:26:24 PM] 		assembly: Assembly 21w06a-1.0.0
[08/01/2022 19:26:24 PM] 		automaticdoors-fabric: Automatic Doors (Fabric) 1.9
[08/01/2022 19:26:24 PM] 		badstdout: BadStdOut 1.1.1-1.18
[08/01/2022 19:26:24 PM] 		balm-fabric: Balm 2.4.0+0
[08/01/2022 19:26:24 PM] 		barkcarpets: Bark Carpets 1.18
[08/01/2022 19:26:24 PM] 		bcdt_expansion: BCDT Expansion 1.18.1-1.1.1
[08/01/2022 19:26:24 PM] 		bclib: BCLib 1.2.1
[08/01/2022 19:26:24 PM] 		bedrockcrafter-fabric: Bedrock Crafter 1.1.3
[08/01/2022 19:26:24 PM] 		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
[08/01/2022 19:26:24 PM] 		bitsandchisels: BitsAndChisels 2.6.1
[08/01/2022 19:26:24 PM] 		config2brigadier: Config to Brigadier 1.0.2
[08/01/2022 19:26:24 PM] 		creativekeybind: CreativeKeybind 1.18.1-fabric-1.0.2
[08/01/2022 19:26:24 PM] 		enhancedblockentities: Enhanced Block Entities 0.5+1.18
[08/01/2022 19:26:24 PM] 		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.0
[08/01/2022 19:26:24 PM] 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
[08/01/2022 19:26:24 PM] 		farmingforblockheads: Farming for Blockheads 9.0.2
[08/01/2022 19:26:24 PM] 		figura: Figura 0.0.7
[08/01/2022 19:26:24 PM] 		languagereload: Language Reload 1.2
[08/01/2022 19:26:24 PM] 		notenoughanimations: NotEnoughAnimations 1.4.0
[08/01/2022 19:26:24 PM] 		omega-config: OmegaConfig 1.0.8
[08/01/2022 19:26:24 PM] 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
[08/01/2022 19:26:24 PM] 		paperdoll: PaperDoll 1.0.0-mc1.18-pre1
[08/01/2022 19:26:24 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreens.register(HandledScreens:76)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66)
[08/01/2022 19:26:24 PM] 	at appeng.init.client.InitScreens.register(InitScreens.java:201)
[08/01/2022 19:26:24 PM] 	at appeng.init.client.InitScreens.init(InitScreens.java:122)
[08/01/2022 19:26:24 PM] 	at appeng.core.AppEngClient.postClientSetup(AppEngClient.java:204)
[08/01/2022 19:26:24 PM] 	at appeng.core.AppEngClient.clientSetup(AppEngClient.java:177)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.handler$cin000$onStart(MinecraftClient:13008)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:712)
[08/01/2022 19:26:24 PM] 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.modify$enb000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:23046)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
[08/01/2022 19:26:24 PM] 	at net.minecraft.client.main.Main.main(Main:238)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[08/01/2022 19:26:24 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08/01/2022 19:26:24 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[08/01/2022 19:26:24 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[08/01/2022 19:26:24 PM] [Render thread/ERROR] Unhandled game exception
[08/01/2022 19:26:24 PM] [Render thread/INFO] Stopping!
[08/01/2022 19:26:24 PM] [CullThread/INFO] [dev.tr7zw.entityculling.CullTask] Shutting down culling task!
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp chisel:blocks
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp ebe:pack
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp phonos:data
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp secretrooms:secret_rooms_data
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp phonos:assets
[08/01/2022 19:26:25 PM] [Render thread/INFO] closing rrp secretrooms:secret_rooms_assets
[08/01/2022 19:26:28 PM] Checking for updated files!

**Comment by TheButterbrotMan** [comment]
#40
