### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by BoBkiNN** [Ladysnake/Effective#60]
mod version 1.1
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10.02.2022, 11:16
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:34)
	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111)
	at net.minecraft.class_638.handler$zhj000$tickWorldAfterBlockEntities(class_638.java:1600)
	at net.minecraft.class_1937.method_18471(class_1937.java:483)
	at net.minecraft.class_638.method_18116(class_638.java:251)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:34)
	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111)
	at net.minecraft.class_638.handler$zhj000$tickWorldAfterBlockEntities(class_638.java:1600)
	at net.minecraft.class_1937.method_18471(class_1937.java:483)
	at net.minecraft.class_638.method_18116(class_638.java:251)

-- Affected level --
Details:
	All players: 1 total; [class_746['BoBkiNN_'/330, l='ClientLevel', x=-45.17, y=63.00, z=-16.50]]
	Chunk stats: 729, 428 F: 20 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-45,63,-14), Section: (at 3,15,2 in -3,3,-1; chunk contains blocks -48,-64,-16 to -33,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 47169 game time, 1000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:517)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, 1.0.0v_VisualFireworks.zip, 3d-torches-v1-3-3.zip, HatStriders_v1.0_2.zip, fresh-pillagers-e280.zip, BetterCarpets.zip, Fabric Mods, Dark_Loading_Screen.zip, VanillaTweaks_r515123.zip, 1.17 panorama pack.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2137765752 bytes (2038 MiB) / 2852126720 bytes (2720 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3,29
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,33
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 24531,10
	Virtual memory used (MB): 15875,89
	Swap memory total (MB): 12264,62
	Swap memory used (MB): 66,70
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		architectury: Architectury 3.2.47
		betterf3: BetterF3 1.2.2
		blue_endless_jankson: jankson 1.2.1
		bobby: Bobby 3.1.0
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.45
		coat: Coat 1.0.0-beta.15
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		crowdin-translate: CrowdinTranslate 1.4+1.18
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		dynamicfps: Dynamic FPS 2.0.6
		effective: Effective 1.1
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		freelook: freelook 1.1.1
		gbfabrictools: GBfabrictools 1.3.4+1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.0.0-dev.20211203.013300
		malilib: MaLiLib 0.10.0-dev.26
		mambience: MAmbience 3.2.0+1.18
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.0
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		optifabric: OptiFabric 1.12.10
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		plasmo_voice: Plasmo Voice 1.2.9
		presencefootsteps: Presence Footsteps 1.4.0
		randomblockplacement: RandomBlockPlacement 1.18-fabric0.43.1-1.1.2
		replaymod: Replay Mod 1.18.1-2.6.3
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		skinlayers: 3d Skin Layers 1.3.1
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.4
		stendhal: Stendhal 1.2.0-1.18
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		waveycapes: WaveyCapes 1.0.4
		xaerominimap: Xaero's Minimap 21.22.3.1
		xaeroworldmap: Xaero's World Map 1.18.6.1
	Launched Version: Fabric 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1018
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/1.0.0v_VisualFireworks.zip (incompatible), file/3d-torches-v1-3-3.zip (incompatible), file/HatStriders_v1.0_2.zip (incompatible), file/fresh-pillagers-e280.zip (incompatible), file/BetterCarpets.zip (incompatible), Fabric Mods, file/Dark_Loading_Screen.zip (incompatible), file/VanillaTweaks_r515123.zip, file/1.17 panorama pack.zip (incompatible)
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 10
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.1
	OptiFine jar version: OptiFine_1.18.1_HD_U_H4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: D:/Users/Rob/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.1_HD_U_H4/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by Theguythatrunstoomuchmods** [comment]
This is not incompatibility or your system. It's a glitch in the mod as it has been reported in other threads
https://github.com/Ladysnake/Effective/issues/40

This thread also has attachments to a patched version done by a 3rd part coder. Enjoy!

**Comment by Akairilia** [comment]
> This is not incompatibility or your system. It's a glitch in the mod as it has been reported in other threads #40
> 
> This thread also has attachments to a patched version done by a 3rd part coder. Enjoy!

hello, I can't seem to find the patched version file. Can you send me the link?

**Comment by drathmorgh** [comment]
> > This is not incompatibility or your system. It's a glitch in the mod as it has been reported in other threads #40
> > This thread also has attachments to a patched version done by a 3rd part coder. Enjoy!
> 
> hello, I can't seem to find the patched version file. Can you send me the link?

I would be very interested in this too!! or ill just wait for the updated fix

**Comment by OverloadedWithMods** [comment]
Sorry for the delayed response. I was busy doing other IRL things. I'll get you it nr

**Comment by OverloadedWithMods** [comment]
I had to compile it manually but I forgot where it was lol. here is the main link to the .jar:
https://www.dropbox.com/s/8sefqw0bx3jeeml/effective-1.2.jar?dl=0
shhhhh..... u never saw this...
